name: marketing-app
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_FB_PIXEL_ID =${NEXT_PUBLIC_FB_PIXEL_ID}
    volumes:
      - ./:/app
