name: Marketing App CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH Agent
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd app/marketing-app
            git pull origin main
            npm run build
            docker-compose up -d --build